### ISSUE TITLE
iOS9 removed SenTestingKit.  SDK won't build

### ISSUE THREAD

**Issue by Danbana** [AuthorizeNet/sdk-ios#31]
Hello,

I haven't been able to use the SDK in Xcode 7, as SenTestingKit has been deprecated and removed by Apple.

How should I proceed.  I've tried the manual install and the Podfile.

Thanks,
Danny

**Comment by Alexandeer** [comment]
This must be corrected immediately. You have not used the tests in the project. Why have you left it all here?

**Comment by brianmc** [comment]
SenTestingKit Removed see PR https://github.com/AuthorizeNet/sdk-ios/pull/32
