### ISSUE TITLE
Not able to integrate the SDK

### ISSUE THREAD

**Issue by EpicommiOS** [AuthorizeNet/sdk-ios#36]
Not even the sample provided by you gets build and not either when i am integrating to my app it gives so  many errors. Will you please help me out with this how to integrate  your SDK manually. I have already read your README documentation but it is of no use for me.

**Comment by brianmc** [comment]
The Sample app should be working now.  It has examples of using the SDK to create an MPOS application as well as how to integrate ApplePay into a consumer mobile app.
You can take the latest Example from master or download release 1.9.8

**Comment by EpicommiOS** [comment]
Hi Team,
Actually what issue I am facing is that sample code you have provided in 
that you ask for *username* and *password* than what is the use 
of*transaction key* and *APILogin key. *As in other languages (except 
objective c)**you ask to pass *transaction key* and *APILogin key* but 
in objective c you ask to login through *username and password*. So 
basically I am getting confused how to make people avaliable to make 
payment through my iOS  app. Please let me know the appropriate steps to 
do so.

Thanks and regards,
Ankit Sharma

**Comment by brianmc** [comment]
Please be aware that the iOS SDK (right now) is purely for card-present (i.e. merchant acceptance) applications.  Transaction key should never be used from a mobile application as it is a shared secret that is solely designed for server-to-server communications.  Please note that we will soon be launching a new iOS SDK that will help developers include payments in their (consumer) mobile applications.

Feel free to reach out to us with more details on your use case at developer@authorize.net, mention my name Brian to make sure it gets to me.

Thanks,

Brian
