### ISSUE TITLE
    "Error.errorCode = 8\nError.errorText = The credit card has expired.\n"

### ISSUE THREAD

**Issue by Moeez007** [AuthorizeNet/sdk-ios#37]
Hello Guys,

I have successfully integrated the SDK in my project, I am using the sample code provided in this link https://github.com/AuthorizeNet/sdk-ios/blob/master/MPOS_README.md
in the "Putting it all together - the sample app" section.

The "loginToGateway" method runs succesfully but the "createTransaction" method returns an error. 

    "Error.errorCode = 8\nError.errorText = The credit card has expired.\n"

Should i use real credit card info, I have tried using dummy credit card info but it does not works.

Any help would be appreciated.

Thanks.

**Comment by brianmc** [comment]
You should be able to use a test card like 4111 1111 1111 1111 but you do need a valid expiry.  Please note this is an SDK for CARD PRESENT transactions and should only be used for building merchant applications, not consumer apps.
