### ISSUE TITLE
Demo does not work

### ISSUE THREAD

**Issue by Moeez007** [AuthorizeNet/sdk-ios#38]
Hello,

I have downloaded the demo project but it wont compile, ANetSolution.h this file is missing.

Can someone please guide me how to resolve this issue.

Thanks

**Comment by ynachti** [comment]
I am having the same issue

**Comment by AtheistP3ace** [comment]
Also having this issue.

**Comment by brianmc** [comment]
We've fixed the issues with the sample app, apologies for the delay.  Pull the latest version from Master, or take release 1.9.8 or use  $>  pod try 'authorizenet-sdk'
